config/routes.rb
Rails.application.routes.draw do


  get '/admindashboard', to: "pages#admin_dashboard", as: "admin_dashboard"
  get '/userdashboard', to: 'pages#user_dashboard', as: 'user_dashboard'


  get 'products/', to: "products#index", as: "products"
  get 'products/new', to:'products#new', as:'new_product'
  post '/products', to:'products#create'
  get 'products/:id', to: "products#show", as:"product"
  get 'products/:id/edit', to:"products#edit", as: "edit_product"
  patch 'products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy'
  get '/admin_products', to: 'products#admin_products', as: 'admin_products'
  

  get '/categories', to: "categories#index", as:"categories"
  get 'categories/new', to:'categories#new', as:'new_category'
  post '/categories', to:'categories#create'
  get '/categories/:id', to: 'categories#show', as:'category'
  patch 'categories/:id', to: 'categories#update'
  delete '/categories/:id', to: 'categories#destroy'
  get 'categories/:id/edit', to:"categories#edit", as: "edit_category"

  get '/brands', to: "brands#index", as:"brands"
  get 'brands/new', to:'brands#new', as:'new_brand'
  post '/brands', to:'brands#create'
  get '/brands/:id', to: 'brands#show', as:'brand'
  patch 'brands/:id', to: 'brands#update'
  delete '/brands/:id', to: 'brands#destroy'
  get 'brands/:id/edit', to:"brands#edit", as: "edit_brand"
 
  # get '/users/:id/user_infos', to:"user_infos#index", as: "user_user_info"
  # patch '/users/:id/user_infos', to:"user_infos#update"
  # delete '/users/:id/user_infos', to:"user_infos#destroy"
  # get '/users/:id/user_infos/edit', to:"user_infos#edit", as: "edit_user_user_info"
  # get '/users/:id/user_infos/new', to:"user_infos#new", as: "new_user_user_info"
  # post '/users/:id/user_infos', to:"user_infos#create"
  # get '/users/:id/order_lines', to:'order_lines#index', as: 'order_lines'
  # post '/users/:id/order_lines', to:'order_lines#create'
  # delete '/users/:id/order_lines', to: 'order_lines#destroy'
  # get '/users/:id/cart', to:'carts#show', as: 'cart'

  get '/payments/success', to: 'payments#success'
  post 'payments/webhook', to: 'payments#webhook'

  get '/', to: "pages#index", as: "root"

  get '/addresses', to: 'addresses#index', as: 'addresses'
  post '/addresses', to: 'addresses#create'
  get '/addresses/new', to: 'addresses#new', as: 'new_address'
  get '/addresses/:id', to: 'addresses#show', as: 'address'
  delete '/addresses/:id', to: 'addresses#destroy'
  get '/addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update'


  devise_for :users, :path_prefix => 'my', controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  } 

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders', to: 'orders#create'
  get '/orders/new', to: 'orders#new', as: 'new_order'
  get '/orders/:id', to: 'orders#show', as: 'order'
  delete '/orders/:id', to: 'orders#destroy'
  get '/orders/:id/edit', to: 'orders#edit', as: 'edit_order'
  patch '/orders/:id', to: 'orders#update'
  

  
  # scope "/admin" do
  #   resources :users, :controller => "users"
  # end

  get '/not_authorised', to: 'pages#not_authorised', as: 'not_authorised'
  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :user_info, :dependent => :destroy
  has_many :products
  has_many :orders
  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :user_info, :addresses, :orders


end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #before actions required to accommodate additional parameters from nested fields in user tables
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super do
    @user.user_info = UserInfo.new #creating new user info object when a new user is created
    @address = @user.addresses.new # creating new address object when a new user is created
    end
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def user_info_params
  #   params.require(:user_info).permit( :user_id, :first_name, :surname, :gender )
  # end



  # If you have extra params to permit, append them to the sanitizer.
  
  #extra params required as fields from address and user info table are nested in the user registration form
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [user_info_attributes: [:first_name, :surname, :gender], addresses_attributes: [:street_number,:suburb, :postcode, :state, :country]])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [user_info_attributes: [:first_name, :surname, :gender], addresses_attributes: [:street_number,:suburb, :postcode, :state, :country]])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource) - take this out if want to go to a page other than root
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_load_resource :only => [:new, :create]

  def index
    @users = User.where.not(:id => current_user.id)
  end

  def new
    #need to create new objects as registration form contains nested fields from UserInfo and Address models
    @user = User.new
    @user.user_info = UserInfo.new
    @address = @user.addresses.new
  end

  def show

  end

  def create
    # allows admins to create user accounts with blank passwords
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    params[:user].delete(:current_password) if params[:user][:password].blank? and params[:user][:password_confirmation].blank? and params[:user][:password_confirmation].blank?
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to @user
    else
      render :new
    end
  end

  def edit

  end

  def update
    # allows admins to update user accounts without requiring passwords
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    params[:user].delete(:current_password) if params[:user][:password].blank? and params[:user][:password_confirmation].blank? and params[:user][:current_password].blank?
    if @user.update(user_params)
      flash[:notice] = "Successfully updated User."
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
  
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to users_path
    else
      flash[:notice] = 'Error: user unable to be deleted'
      redirect_to users_path
    end
  end 

  private

  def user_params
    #sanitised params to permit attributes from UserInfo and Address models to enable nested form fields to submit data to these tables
     params.require(:user).permit(:email, :password, :password_confirmation,:current_password, :admin, user_info_attributes: [:first_name, :surname, :gender], addresses_attributes: [:street_number,:suburb, :postcode, :state, :country])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%= form_with(model: user, local:true) do |f| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
</div>
<br>
Admin User&#63; <%= f.check_box :admin %>
<br>
<br>

<%= f.fields_for :user_info do |u| %>
<div class="field">
  <%= u.label :first_name %><br>
  <%= u.text_field :first_name %>
</div>

<div class="field">
  <%= u.label :surname %><br>
  <%= u.text_field :surname %>
</div>

<div class="field">
  <%= u.label :gender %><br>
  <% UserInfo.genders.keys.each do |g|%>
  <%= u.label g %>
  <%= u.radio_button :gender, g %>
  <% if g == user.user_info.gender %>
  <% u.radio_button :gender, :checked => true %>
  <% end %>
  <% end %>
</div>
<% end %>
<br>
<div class="field">
  <%= f.label :password %> <br />
  <%= f.password_field :password, autocomplete: "new-password" %>
  <% if @minimum_password_length %>
  <br />
  <em><%= @minimum_password_length %> characters minimum</em>
  <% end %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</div>
<br>
<div class="actions">
  <%= f.submit "Submit" %>
</div>
<% end %>
<br>

app/views/users/edit.html.erb
<div class="row one">
  <h1>Editing information for <%= @user.email%></h1>
</div>
<div class="form-row">
  <div class="productform">
    <%= render 'user_form', user: @user %>

    <h2>Addresses</h2>
    <% if @user.addresses.any? %>
    <%@user.addresses.each do |address| %>
    <% counter = 1%>
    <b><%= "Address #{counter}: " %></b><br>
    <%= address.street_number%>
    <br>
    <%= address.suburb%>,
    <%= address.state%> <%= address.postcode%>
    <br>
    <%= address.country%>
    <br>
    <% counter += 1%>
    <% end%>
    <br>
    <% else %>
    There are no addresses recorded for this user yet
    <br>
    <% end%>
    <%= link_to 'Manage Addresses', addresses_path(@user) %>
    <br>
    <%= link_to 'Admin Dashboard', admin_dashboard_path %>
    <br>
    <%= link_to 'Manage Users', users_path %>

  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <h1>All Users</h1>
</div>
<div class="row">
  <h3><%= link_to 'Add new user', new_user_path %></h3>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>User ID</th>
        <th>Email</th>
        <th>Date Registered</th>
        <th>Admin?</th>
        <th>View Details</th>
        <th>Edit User</th>
        <th>Delete User</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.id%></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.localtime.to_date%></td>
        <td><%= user.admin %>
        <td><%= link_to 'View Details', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render 'user_form', user: @user %>

<h2>Addresses</h2>
<% if @user.addresses.first.id == nil %>
An address is required for purchases
<br>
<% else %>
<%@user.addresses.each do |address| %>
<% counter = 1%>
<%= "Address #{counter}: " %><br>
<%= address.street_number%>
<br>
<%= address.suburb%>,
<%= address.state%> <%= address.postcode%>
<br>
<%= address.country%>
<br>
<% counter += 1%>
<% end%>
<% end%>
<%= link_to 'Manage Addresses', addresses_path(@user) %>
<br>

<%= link_to 'Back', :back %>
<br>
<%= link_to 'Admin Dashboard', admin_dashboard_path %>

app/views/users/show.html.erb
<h2> Viewing information for <%= @user.email%> </h2>

Date registered: <%= @user.created_at.localtime.to_date%><br>
Email: <%=@user.email%><br>
<h3> User Information </h3>
<% if @user.user_info == nil%>
  User information not recorded
<% else %>
  <b>First Name:</b> <%= @user.user_info.first_name %><br>
  <b>Last Name:</b> <%= @user.user_info.surname %><br>
  <b>Gender:</b> <%= @user.user_info.gender %><br>
<% end %>

<br>
<h2>Addresses</h2>
<% if @user.addresses.any? %>
  <%@user.addresses.each do |address| %>
    <% counter = 1%>
    <b>Address <%=counter%>:</b><br>
    <%= address.street_number%>
    <br>
    <%= address.suburb%>,
    <%= address.state%> <%= address.postcode%>
    <br>
    <%= address.country%>
    <br>
    <% counter += 1%>
    <br>
  <% end%>
<% else %>
  There are no addresses recorded for this user yet
  <br>
<%end%>

<%= link_to "Back", :back %>
<br>
<%= link_to 'Admin Dashboard', admin_dashboard_path %>