config/routes.rb
Rails.application.routes.draw do


  get '/admindashboard', to: "pages#admin_dashboard", as: "admin_dashboard"
  get '/userdashboard', to: 'pages#user_dashboard', as: 'user_dashboard'


  get 'products/', to: "products#index", as: "products"
  get 'products/new', to:'products#new', as:'new_product'
  post '/products', to:'products#create'
  get 'products/:id', to: "products#show", as:"product"
  get 'products/:id/edit', to:"products#edit", as: "edit_product"
  patch 'products/:id', to: 'products#update'
  delete '/products/:id', to: 'products#destroy'
  get '/admin_products', to: 'products#admin_products', as: 'admin_products'
  

  get '/categories', to: "categories#index", as:"categories"
  get 'categories/new', to:'categories#new', as:'new_category'
  post '/categories', to:'categories#create'
  get '/categories/:id', to: 'categories#show', as:'category'
  patch 'categories/:id', to: 'categories#update'
  delete '/categories/:id', to: 'categories#destroy'
  get 'categories/:id/edit', to:"categories#edit", as: "edit_category"

  get '/brands', to: "brands#index", as:"brands"
  get 'brands/new', to:'brands#new', as:'new_brand'
  post '/brands', to:'brands#create'
  get '/brands/:id', to: 'brands#show', as:'brand'
  patch 'brands/:id', to: 'brands#update'
  delete '/brands/:id', to: 'brands#destroy'
  get 'brands/:id/edit', to:"brands#edit", as: "edit_brand"
 
  # get '/users/:id/user_infos', to:"user_infos#index", as: "user_user_info"
  # patch '/users/:id/user_infos', to:"user_infos#update"
  # delete '/users/:id/user_infos', to:"user_infos#destroy"
  # get '/users/:id/user_infos/edit', to:"user_infos#edit", as: "edit_user_user_info"
  # get '/users/:id/user_infos/new', to:"user_infos#new", as: "new_user_user_info"
  # post '/users/:id/user_infos', to:"user_infos#create"
  # get '/users/:id/order_lines', to:'order_lines#index', as: 'order_lines'
  # post '/users/:id/order_lines', to:'order_lines#create'
  # delete '/users/:id/order_lines', to: 'order_lines#destroy'
  # get '/users/:id/cart', to:'carts#show', as: 'cart'

  get '/payments/success', to: 'payments#success'
  post 'payments/webhook', to: 'payments#webhook'

  get '/', to: "pages#index", as: "root"

  get '/addresses', to: 'addresses#index', as: 'addresses'
  post '/addresses', to: 'addresses#create'
  get '/addresses/new', to: 'addresses#new', as: 'new_address'
  get '/addresses/:id', to: 'addresses#show', as: 'address'
  delete '/addresses/:id', to: 'addresses#destroy'
  get '/addresses/:id/edit', to: 'addresses#edit', as: 'edit_address'
  patch '/addresses/:id', to: 'addresses#update'


  devise_for :users, :path_prefix => 'my', controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  } 

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  get '/orders', to: 'orders#index', as: 'orders'
  post '/orders', to: 'orders#create'
  get '/orders/new', to: 'orders#new', as: 'new_order'
  get '/orders/:id', to: 'orders#show', as: 'order'
  delete '/orders/:id', to: 'orders#destroy'
  get '/orders/:id/edit', to: 'orders#edit', as: 'edit_order'
  patch '/orders/:id', to: 'orders#update'
  

  
  # scope "/admin" do
  #   resources :users, :controller => "users"
  # end

  get '/not_authorised', to: 'pages#not_authorised', as: 'not_authorised'
  get "*path", to: "pages#not_found", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    can :read, Product, public: true
    can :read, Category, public: true
    can :read, Brand, public: true
    can :read, Ingredient, public: true


    if user.present?  # additional permissions for logged in users (they can read their own posts)
      can :read, Product
      can :read, Category
      can :read, Brand
      can :read, Ingredient
      can :read, :create, Order, user_id: user.id
      can :crud, Product, user_id: user.id
      can :crud, ProductIngredient
      can :crud, UserInfo, user_id: user.id
      can :crud, Address, user_id: user.id
      if user.admin?
        can :manage, :all 
      end
    end

 
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :product_ingredients, :dependent => :destroy
  has_many :products, through: :product_ingredients
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lines, :dependent => :destroy
  accepts_nested_attributes_for :order_lines
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :product
  belongs_to :order
  accepts_nested_attributes_for :order
end

app/models/product.rb
class Product < ApplicationRecord
 
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  has_one :order_line
  has_one_attached :picture
  has_one_attached :receipt
  has_many :product_ingredients, :dependent => :destroy
  has_many :ingredients, through: :product_ingredients
  serialize :ingredients
  enum used: { no:0, yes:1 }
  accepts_nested_attributes_for :ingredients, :brand, :category
  validates :brand, length: { in: 1..60, message: "must be between 1 and 60 characters"  }
  validates :name, length: { in: 3..60, message: "must be between 3 and 60 characters"  }
  validates :description, length: { in: 20..255, message: "must be between 20 and 255 characters" }
  validates :price, numericality: { greater_than_or_equal_to: 5, message: "must be at least $5"  }
  validates :name, :description, :category, :brand, :used, :price, :picture, presence: true 
  validates :expiry_date, :receipt, presence: true, if: Proc.new { |product| product.used == 'yes'}
  

end

app/models/product_ingredient.rb
class ProductIngredient < ApplicationRecord
  belongs_to :product
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :user_info, :dependent => :destroy
  has_many :products
  has_many :orders
  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :user_info, :addresses, :orders


end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  enum gender: { female:2, male:4 }

  validates :first_name, presence: true, length: { maximum: 50, message: "maximum of 50 characters" } 

  validates :surname, presence: true, length: { maximum: 50, message: "maximum of 50 characters" } 


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_side_nav.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'KSC', root_path,class:"navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"nav-link") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class:"nav-link") %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
      <li class="nav-item">
        <% if current_user.admin == false %>
        <%= link_to 'My Dashboard', user_dashboard_path, class:"nav-link" %>
        <% else %>
        <%= link_to 'Admin Dashboard', admin_dashboard_path, class:"nav-link" %>
        <% end %>
      </li>
      <%end%>
      <li class="nav-item">
        <%= link_to 'Sell Product', new_product_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Shop Products', products_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
        <%= link_to('Edit registration', edit_user_registration_path, class:"nav-link") %>
        <% else %>
        <%= link_to('Register', new_user_registration_path, class:"nav-link") %>
        <% end %>
      </li>
    </ul>
  </div>
  <span class="navbar-text">
    <%= notice %>
    <% if user_signed_in? %>
    Logged in as <%= current_user.email%>
    <% end %>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>KSC Marketplace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application.js"%>
</head>

<body>
  <div class="container-fluid">
    <%= render "/layouts/top_nav" %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
</body>

</html>

app/views/pages/admin_dashboard.html.erb
<div class="row one">
  <h1>Administrator Dashboard </h1>
</div>
<div class="row dashboard">
  <div class="card" style="width: 15rem;">
    <i class="fas fa-users-cog card-img-top porticon"></i>
    <div class="card-body diffbg">
      <h5 class="card-title">Manage Users</h5>
      <p class="card-text">
        <ul>
          <li>View list of users</li>
          <li>Edit user Details</li>
          <li>Delete users</li>
          <li>Add new users </li>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Manage Users', users_path, class:"btn btn-outline-dark" %>
    </div>
  </div>

  <div class="card" style="width: 15rem;">
    <i class="far fa-folder-open card-img-top porticon"></i>
    <div class="card-body diffbg">
      <h5 class="card-title">Manage Categories</h5>
      <p class="card-text">
        <ul>
          <li>View categories</li>
          <li>Edit categories</li>
          <li>Delete categories</li>
          <li>Add new categories </li>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Manage Categories', categories_path, class:"btn btn-outline-dark" %>
    </div>
  </div>

  <div class="card" style="width: 15rem;">
    <i class="fas fa-trademark card-img-top porticon"></i>
    <div class="card-body diffbg">
      <h5 class="card-title">Manage Brands</h5>
      <p class="card-text">
        <ul>
          <li>View brands</li>
          <li>Edit brands</li>
          <li>Delete brands</li>
          <li>Add new brands </li>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Manage Brands', brands_path, class:"btn btn-outline-dark" %>
    </div>
  </div>

  <div class="card" style="width: 15rem;">
    <i class="fas fa-shopping-basket card-img-top porticon"></i>
    <div class="card-body diffbg">
      <h5 class="card-title">Manage Product Listings</h5>
      <p class="card-text">
        <ul>
          <li>View all current and previous product listings</li>
          <li>Edit product listings</li>
          <li>Delete product listings</li>
          <li>Add new product listings </li>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Manage Product Listings', admin_products_path, class:"btn btn-outline-dark" %>
    </div>
  </div>

  <div class="card" style="width: 15rem;">
    <i class="fas fa-shopping-cart card-img-top porticon"></i>
    <div class="card-body diffbg">
      <h5 class="card-title">Manage Orders</h5>
      <p class="card-text">
        <ul>
          <li>View all current and previous orders for all users</li>
          <li>Edit orders</li>
          <li>Delete orders</li>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Manage Orders', orders_path, class:"btn btn-outline-dark" %>
    </div>
  </div>

app/views/pages/index.html.erb
<div class="jumbotron jumbotron-cover-image">
  <div class="container">
    <h1 class="imgtext">Welcome to the Korean Skin Care Marketplace</h1>
    <p class="imgtext">A place for buying and selling Korean skin care</p>
    <%= link_to 'Shop Now', products_path, class:"btn btn-outline-dark", role:"button" %>
  </div>
</div>
</div>
<div class="row one">
  <h2>Recent Product Listings</h2>
</div>
<div class="row">
  <% @recent_products.each do |product|%>
  <div class="card" style="width: 18rem;">
    <%= image_tag product.picture, class:"card-img-top", alt:"Card image cap" %>
    <div class="card-body diffbg">
      <h5 class="card-title"><%= product.name %> <%= number_to_currency(product.price) %></h5>
      <p class="card-text"><%= product.description%></p>
    </div>
    <div class="card-footer">
      <%= link_to 'View Details', product_path(product), class:"btn btn-outline-dark" %>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/pages/not_authorised.html.erb
<h1> You are not authorized to view this page </h1>
<br>
<%= link_to 'Go Back', :back %>
<br>
<%= link_to 'Home Page', root_path %>

app/views/pages/not_found.html.erb
Page not found.

<%= link_to 'Home', root_path %>

app/views/pages/user_dashboard.html.erb
<div class="row">
  <h1>Welcome to your dashboard </h1>
</div>
<div class="row">
  <h3> Current Product Listings </h3>
</div>
<div class="row">
  <% if @current_products.any? %>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Product ID</th>
        <th>Category</th>
        <th>Brand</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Date Listed </th>
        <th>Price </th>
        <th colspan="10"></th>

    </thead>
    <tbody>
      <% @current_products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.category.name %></td>
        <td><%= product.brand.name %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.created_at.localtime.to_date%></td>
        <td><%= number_to_currency(product.price) %></td>


        <td><%= link_to 'View Details', product_path(product) %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% else %>
  <h5> You have no current product listings </h5>
  <% end %>
  <br>
</div>

<div class="row">
  <h3>Previous Product Listings </h3>
</div>
<div class="row">
  <% if @previous_products.any? %>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Product ID</th>
        <th>Category</th>
        <th>Brand</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Date Listed </th>
        <th>Date Sold</th>
        <th>Price </th>
        <th colspan="9"></th>

    </thead>
    <tbody>
      <% @previous_products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.category.name %></td>
        <td><%= product.brand.name %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.created_at.localtime.to_date%></td>
        <td><%= product.order_line.created_at.localtime.to_date%></td>
        <td><%= number_to_currency(product.price) %></td>


        <td><%= link_to 'View Details', product_path(product) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% else %>
  <h5> You have no product listing history to display </h5>
  <% end %>
  <br>
</div>
<div class="row">
  <h3>Order History </h3>
</div>
<div class="row">
  <% if current_user.orders.any? %>
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Order ID</th>
        <th>Date Ordered</th>
        <th>Total Amount</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% current_user.orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.created_at.localtime.to_date %></td>
        <td><%= number_to_currency(order.total_amount) %></td>
        <td><%= link_to 'View Details', order_path(order) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% else %>
  <h5> There is no order history to display </h5>
  <% end %>
  <br>
</div>
<%= link_to 'Back', :back %>
</div>